/*

 This file is part of CaptureTheData!

 Copyright (c) 2011, Bobbie Smulders

 Contact:  mail@bsmulders.com

 GNU General Public License Usage
 This file may be used under the terms of the GNU General Public License version 3.0 as published by the Free Software Foundation and appearing in the file LICENSE included in the packaging of this file.  Please review the following information to ensure the GNU General Public License version 3.0 requirements will be met: http://www.gnu.org/copyleft/gpl.html.

 */

#ifndef __CTD_WII_H__
#define __CTD_WII_H__

/**
 * Connect to the Wiimote and log all data to the database
 * @param device 	Bluetooth MAC address of the Wiimote to connect to
 * @param database 	The path to the database
 * @param tripid 	The trip id of the trip to log to
 * @return			0 on succes, -1 on failure
 */
int log_wii(char * device, char * database, int tripid);

/**
 * Parse the data previously generated by log_wii
 * @param database 	The path to the database
 * @param tripid 	The trip id of the trip to parse data from
 * @return			0 on succes, -1 on failure
 */
int parse_wii(char * database, int tripid);

/**
 * Generate measurement reports from parsed data
 * @param database 	The path to the database
 * @param tripid 	The trip id of the trip to generate reports for
 * @return			0 on succes, -1 on failure
 */
int generate_wii_report(char * database, int tripid);

#endif
